services:
  postgres:
    image: postgres:15
    container_name: rama_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rama_db
      POSTGRES_USER: rama_user
      POSTGRES_PASSWORD: rama_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rama_net

  app:
    build: .
    container_name: rama_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rama_db
      SPRING_DATASOURCE_USERNAME: rama_user
      SPRING_DATASOURCE_PASSWORD: rama_pass
    networks:
      - rama_net

volumes:
  postgres_data:

networks:
  rama_net:

